name: esempio workfolw

on: [push]

jobs: 
  build:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
    - uses: actions/checkout@v2
    - name: run a one-line script
      run: echo Hello, world!
